### ISSUE TITLE
Save error for some games

### ISSUE THREAD

**Issue by wolfokami321** [benvanik/xenia#653]
I thought it might be a better idea to bring this issue to the main git, seeing how this may effect more than just one game. I ran xenia in administrator mode, and made sure all files had read-only unchecked, yet I still have write-access issues with this game in particular. Tenchu Z, this did not happen in a previous builds and it seems to be a regression of some sort related to xbl sign in?

As referenced in game compatibility:
https://github.com/xenia-project/game-compatibility/issues/592

![save failed](https://cloud.githubusercontent.com/assets/10334571/21598282/1d10761c-d195-11e6-8683-b02e7d8d7608.jpg)

**Comment by Blackbird88** [comment]
Did Xenia ever emulate the HDD filesystem? Saints Row doesn't see any HDDs.

**Comment by DrChat** [comment]
This may be fixed as of 8ccefa160076c13a1cb4e2a8e1d7fc7e254a6b4b. Go ahead and check these games again.

**Comment by Parovozik** [comment]
Still troubles for TenchuZ, Sonic Unleashed, Digimon All Star Rumble

**Comment by LuismaSP89** [comment]
Some games with save/load problems include Bayonetta, Eternal sonata, Rayman origins, etc.

**Comment by Parovozik** [comment]
This specific trouble, i know 3 games when this error - Nier, TenchuZ, Sonic Unleashed (maybe Digimon all Star Rumble too). There not enough rights to create primary content (initialization), I do not know why, it's just a fact, and if you put the right save files, then everything works correctly (downloading, creating new ones)
Proof:
![xenia tenchu_z mp4_snapshot_02 18_ 2018 03 05_01 59 47](https://user-images.githubusercontent.com/19775644/36952430-04f296ce-2021-11e8-9a7e-4d2f45e2e915.jpg)

**Comment by LuismaSP89** [comment]
@Parovozik, Sorry, but, how do you managed to do that? I have a lot of savegames from my Xbox 360 (Extracted with Horizon) and I put in the "Content" folder of Xenia (Inside of the respective subfolder with the codename of the game, for example, Bayonetta is: Content/53450813/00000001 

Tested with/without the files in the subfolder 00000001 and no file appear in game. 

How is your folder structure for your save files in xenia? Thanks in advance!

**Comment by Parovozik** [comment]
@LuismaSP89 'TENCHU_Z' not final file, thie package. Just ectract all from.
Correct structure:
- xenia\content\465307D7\00000001\TENCHU_Z\tenchu.bin
- xenia\content\465307D7\00000001\TENCHU_Z\__Thumbnail.png
.
i tried many games and think what error with save-states there if should shown system dialog 'Choose your device', but this not works (not realized on xenia or works incorect)
Some games as Sonic U, Tenchu Z not show dialog 'choose your device' if save-states found on default path and all works correctly.
Other games will show 'choose your device' dialog anyway and then save-states not works and sometimes game too (wait until answer from 'choose your device')

**Comment by LuismaSP89** [comment]
Ok, this problem is solved (At least for me) now the emulator saves properly (First I needed to remove the content folder) and bayonetta can save normally.

The only problem for me now is to transfer the savestates from xbox 360 to the emulator ones (I used Horizon to export saves to PC, but the size of the files are bigger than the emulator ones, and if I try to replace and start the game, it says that is corrupted) maybe I´ll need to decrypt the saves or something...

**Comment by Mirai27** [comment]
> @LuismaSP89 'TENCHU_Z' not final file, this package. Just extract all from.
> Correct structure:
> 
> * xenia\content\465307D7\00000001\TENCHU_Z\tenchu.bin
> * xenia\content\465307D7\00000001\TENCHU_Z\ __Thumbnail.png
>   Equally for save-states Dante Inferno - requires extract
>   .
>   ![bandicam 2018-03-06 18-30-05-871](https://user-images.githubusercontent.com/19775644/37041112-7295e0b8-216c-11e8-92ca-8d3e87842792.jpg)
> 
> .
> i tried many games and think what error with save-states there if should shown system dialog 'Choose your device', but this not works (not realized on xenia or works incorrect)
> Some games as Sonic U, Tenchu Z not show dialog 'choose your device' if save-states found on default path and all works correctly.
> Other games will show 'choose your device' dialog anyway and then save-states not works and sometimes game too (wait until answer from 'choose your device')

Паровозик, вы ведь русский? Помоги как фанату соника поже) Не подскажешь полное название папки куда сейв кидать и как? И если не трудно кинь сам сейв а то у меня в формате SYS-DATA буду очень рад)

**Comment by Parovozik** [comment]
@Mirai27 Hi. Just use Xenia-Vulkan full pack, there included saves for some games (SonicU, TenchuZ...). 
https://drive.google.com/open?id=1cd_Qw-TEzjcbm0Ik5gBN6snCiZMvbkPk

**Comment by Mirai27** [comment]
Большое спасибо но паровозик ник же у вас на русском почему же отвечаете на английском а вообще спасибо. я на 7 небе от счастья!

**Comment by Dantedunzell** [comment]
Does someone have information about Ninja Gaiden 3 Razor's Edge? I still have the same issue with ''Choose the folder that you will use to storage'' I don't have any Xbox 360 to move the saved game files, if maybe some of you have it and can share it with me here I will be very thankful. thanks

**Comment by Dantedunzell** [comment]
Do you guys have a saved game for Ninja Gaiden 3 ?

**Comment by shrek-lab** [comment]
Dump it from your Xbox 360

**Comment by Margen67** [comment]
@Dantedunzell GitHub isn't for tech support. Stop spamming.

**Comment by Dantedunzell** [comment]
I am not asking for tech support I am asking if someone was able to solve the issues saving games an has some data that can be shared I am not asking anybody to solve my problem, in fact, if I solved it, it will be good for all of us since I will be posting the solution to play it.

**Comment by shrek-lab** [comment]
Well this is not the place for that

**Comment by Coldman321** [comment]
Having issues with EA Sports MMA, same thing regarding the saves.

**Comment by Intrixod** [comment]
> Having issues with EA Sports MMA, same thing regarding the saves.
> ![Screenshot_16](https://user-images.githubusercontent.com/57199220/67903015-cf07a280-fb6a-11e9-82f6-1faca03c7767.png)

I also have the same problem, same message, with Fight Night Champion. Were you able to solve it?

**Comment by Margen67** [comment]
@Intrixod GitHub isn't for tech support. Go to the [Discord server](https://discord.gg/5g93S8H) for that.
